# Server configurations
server:
  enviroment: "development"
  host: "localhost"
  port: 8000

# Database credentials
database:
  connectionString: "mongodb://root:example@mongo:27017/"
  database: "full-arch"

# Messaging service
messaging:
  url: "pulsar://localhost:6650"